name: Build Mod (Forge 1.16.5)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.9
      - run: gradle --no-daemon --stacktrace --info clean build
      - uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
